//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikNetLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/Muayene/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WebReference_Muayene_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WebReference_Muayene_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/VatandasYabanciKayit/services/MCCI_AR000001TR_S" +
            "ervice")]
        public string SaglikNetLib_WebReference_VatandasYabanciHastaKayit_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WebReference_VatandasYabanciHastaKayit_MCCI_AR000001TR_Service"]));
            }
        }
    }
}
