//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikNetLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/VatandasYabanciKayit/services/MCCI_AR000001TR_S" +
            "ervice")]
        public string SaglikNetLib_WSVatandasYabanciHastaKayit_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSVatandasYabanciHastaKayit_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/Muayene/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSMuayene_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSMuayene_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/KadinIzlem/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WS1549YasKadinIzlem_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WS1549YasKadinIzlem_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/AgizveDisSagligi/services/MCCI_AR000001TR_Servi" +
            "ce")]
        public string SaglikNetLib_WSAgizVeDisSagligi_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSAgizVeDisSagligi_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/Asi/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSAsi_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSAsi_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/BebekCocukBeslenme/services/MCCI_AR000001TR_Ser" +
            "vice")]
        public string SaglikNetLib_WSBebekCocukBeslenme_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSBebekCocukBeslenme_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/BebekCocukIzlem/services/MCCI_AR000001TR_Servic" +
            "e")]
        public string SaglikNetLib_WSBebekCocukIzlem_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSBebekCocukIzlem_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/BebekCocukPsikososyalIzlem/services/MCCI_AR0000" +
            "01TR_Service")]
        public string SaglikNetLib_WSBebekCocukPsikososyalIzlem_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSBebekCocukPsikososyalIzlem_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wws.sagliknet.saglik.gov.tr/BulasiciHastalikKesinVakaBildirimi/services/MC" +
            "CI_AR000001TR_Service")]
        public string SaglikNetLib_WSBulasiciHastalikKesinVakaBildirimi_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSBulasiciHastalikKesinVakaBildirimi_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/BulasiciHastalikOlasiVakaBildirimi/services/MCC" +
            "I_AR000001TR_Service")]
        public string SaglikNetLib_WSBulasıcıHastalikOlasiVakaBildirimi_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSBulasıcıHastalikOlasiVakaBildirimi_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/Diyabet/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSDiyabet_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSDiyabet_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/DiyalizBildirim/services/MCCI_AR000001TR_Servic" +
            "e")]
        public string SaglikNetLib_WSDiyalizBildirim_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSDiyalizBildirim_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/DiyalizIzlem/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSDiyalizIzlem_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSDiyalizIzlem_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/DogumBildirim/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSDogumBildirim_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSDogumBildirim_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/GebeIzlem/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSGebeIzlem_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSGebeIzlem_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/GebePsikososyalIzlem/services/MCCI_AR000001TR_S" +
            "ervice")]
        public string SaglikNetLib_WSGebePsikososyalIzlem_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSGebePsikososyalIzlem_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/GebelikSonucu/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSGebelikSonucu_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSGebelikSonucu_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/HastaOzlukBilgileri/services/MCCI_AR000001TR_Se" +
            "rvice")]
        public string SaglikNetLib_WSHastaOzlukBilgileri_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSHastaOzlukBilgileri_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/Kanser/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSKanser_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSKanser_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/LohusaIzlem/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSLohusaIzlem_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSLohusaIzlem_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/OlumBildirim/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSOlumBildirim_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSOlumBildirim_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/TetkikSonucu/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSTetkikSonucu_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSTetkikSonucu_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/VatansizKayit/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSVatansizHastaKayit_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSVatansizHastaKayit_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/YatanHasta/services/MCCI_AR000001TR_Service")]
        public string SaglikNetLib_WSYatanHasta_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSYatanHasta_MCCI_AR000001TR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.sagliknet.saglik.gov.tr/YenidoganKayit/services/MCCI_AR000001TR_Service" +
            "")]
        public string SaglikNetLib_WSYenidoganHastaKayit_MCCI_AR000001TR_Service {
            get {
                return ((string)(this["SaglikNetLib_WSYenidoganHastaKayit_MCCI_AR000001TR_Service"]));
            }
        }
    }
}
